import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vue from "esbuild-plugin-vue3";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: {
			js: banner,
		},
		define: {
			// turn off vue hmr
			"process.env.NODE_ENV": '"production"',
		},
		plugins: [vue()],
		entryPoints: ["src/plugin.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		watch: !prod,
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		minify: prod ? true : false,
		treeShaking: true,
		outfile: "main.js",
	})
	.catch(() => process.exit(1));

// scss
await esbuild.build({
	entryPoints: ["./src/styles.scss"],
	plugins: [sassPlugin()],
	outfile: "styles.css",
	watch: !prod,
	bundle: true,
	allowOverwrite: true,
	minify: false,
});
